### ISSUE TITLE
Create all snapshot branches here

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/crates.io-index-archive#3]
I have created here these branches:

- snapshot-2018-09-26
- snapshot-2019-10-17 
- snapshot-2020-03-25
- snapshot-2020-08-04 
- snapshot-2020-11-20 
- snapshot-2021-05-05 
- snapshot-2021-07-02
- snapshot-2021-09-24 
- snapshot-2021-12-21

I would like a second set of eyes to verify this and then close this issue.

**Comment by emilyalbini** [comment]
Confirmed all branches were properly migrated:

```bash
diff -u <(git ls-remote https://github.com/rust-lang/crates.io-index | grep refs/heads/snapshot) <(git ls-remote https://github.com/rust-lang/crates.io-index-archive | grep refs/heads/snapshot)
```
