### ISSUE TITLE
Respond to GH email with timeline

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/crates.io-index-archive#5]
someone needs to reply to the email from GitHub telling them our timeline and giving them permission to delete the pull requests on that repo as well.

**Comment by carols10cents** [comment]
https://github.com/rust-lang/crates-io-cargo-teams/issues/47#issuecomment-506527719

**Comment by carols10cents** [comment]
And ask if they can move the PRs to this repo instead of deleting them.

**Comment by jtgeibel** [comment]
Unfortunately, I'm able to replicate the behavior that @Eh2406 mentions in https://github.com/rust-lang/blog.rust-lang.org/pull/925#issuecomment-1036526076. Without a snapshot branch, git clients will redownload all objects, even if the new HEAD commit points to the exact same tree object.

I wonder if a middle ground might work. Where we create a snapshot branch but drop it from the main repo after 1 week. That way frequent users (and CI that caches the index) will have an opportunity to switch during the O(1) window. I can't really speak to the potential server-side impacts, but during this time the new chain of commits should be small so any server-side re-compression is hopefully low impact.

Maybe we should ask GH support if they have any concerns with that approach, and they could monitor and provide feedback during our next squash cycle to see if it is a viable tradeoff.

**Comment by carols10cents** [comment]
I've responded to the email and cced the crates.io team; I'll open new issues if there's anything that changes when they respond to my email.

**Comment by Eh2406** [comment]
If we switch to getting `O(N)` downloads, the bug reports are gonna come to the cargo team. I don't think we have to be in on the emails, but do let us know what the resolution is.
