### ISSUE TITLE
[longer term] Increase priority of serving the index as static files over HTTP

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/crates.io-index-archive#6]
Could the foundation assist in funding this? Could this come out of the crates.io maintenance budget?

- https://github.com/rust-lang/rfcs/pull/2789
- https://github.com/rust-lang/cargo/issues/9069
- https://github.com/rust-lang/cargo/pull/8890

**Comment by 0xPoe** [comment]
@carols10cents I guess we can close this issue now.

**Comment by carols10cents** [comment]
🎉 Great find!
